// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Athlete struct {
	ID             int64
	Name           string
	Grade          sql.NullInt64
	PersonalRecord sql.NullString
	Events         sql.NullString
}

type Meet struct {
	ID       int64
	Name     string
	Date     sql.NullString
	Location sql.NullString
}

type Result struct {
	ID        int64
	AthleteID sql.NullInt64
	MeetID    sql.NullInt64
	Time      sql.NullString
	Place     sql.NullInt64
}
