// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createAthlete = `-- name: CreateAthlete :one
INSERT INTO athletes (name, grade, personal_record, events)
VALUES (?, ?, ?, ?)
RETURNING id, name, grade, personal_record, events
`

type CreateAthleteParams struct {
	Name           string
	Grade          sql.NullInt64
	PersonalRecord sql.NullString
	Events         sql.NullString
}

func (q *Queries) CreateAthlete(ctx context.Context, arg CreateAthleteParams) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, createAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
	)
	return i, err
}

const createMeet = `-- name: CreateMeet :one
INSERT INTO meets (name, date, location)
VALUES (?, ?, ?)
RETURNING id, name, date, location
`

type CreateMeetParams struct {
	Name     string
	Date     sql.NullString
	Location sql.NullString
}

func (q *Queries) CreateMeet(ctx context.Context, arg CreateMeetParams) (Meet, error) {
	row := q.db.QueryRowContext(ctx, createMeet, arg.Name, arg.Date, arg.Location)
	var i Meet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Location,
	)
	return i, err
}

const createResult = `-- name: CreateResult :one
INSERT INTO results (athlete_id, meet_id, time, place)
VALUES (?, ?, ?, ?)
RETURNING id, athlete_id, meet_id, time, place
`

type CreateResultParams struct {
	AthleteID sql.NullInt64
	MeetID    sql.NullInt64
	Time      sql.NullString
	Place     sql.NullInt64
}

func (q *Queries) CreateResult(ctx context.Context, arg CreateResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, createResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
	)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.MeetID,
		&i.Time,
		&i.Place,
	)
	return i, err
}

const deleteAthlete = `-- name: DeleteAthlete :exec
DELETE FROM athletes WHERE id = ?
`

func (q *Queries) DeleteAthlete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAthlete, id)
	return err
}

const deleteMeet = `-- name: DeleteMeet :exec
DELETE FROM meets WHERE id = ?
`

func (q *Queries) DeleteMeet(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMeet, id)
	return err
}

const deleteResult = `-- name: DeleteResult :exec
DELETE FROM results WHERE id = ?
`

func (q *Queries) DeleteResult(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResult, id)
	return err
}

const getAllAthletes = `-- name: GetAllAthletes :many
SELECT id, name, grade, personal_record, events FROM athletes ORDER BY name
`

func (q *Queries) GetAllAthletes(ctx context.Context) ([]Athlete, error) {
	rows, err := q.db.QueryContext(ctx, getAllAthletes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Athlete
	for rows.Next() {
		var i Athlete
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Grade,
			&i.PersonalRecord,
			&i.Events,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMeets = `-- name: GetAllMeets :many
SELECT id, name, date, location FROM meets ORDER BY date
`

func (q *Queries) GetAllMeets(ctx context.Context) ([]Meet, error) {
	rows, err := q.db.QueryContext(ctx, getAllMeets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meet
	for rows.Next() {
		var i Meet
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllResults = `-- name: GetAllResults :many
SELECT id, athlete_id, meet_id, time, place FROM results ORDER BY id
`

func (q *Queries) GetAllResults(ctx context.Context) ([]Result, error) {
	rows, err := q.db.QueryContext(ctx, getAllResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Result
	for rows.Next() {
		var i Result
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Time,
			&i.Place,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAthleteByID = `-- name: GetAthleteByID :one
SELECT id, name, grade, personal_record, events FROM athletes WHERE id = ? LIMIT 1
`

func (q *Queries) GetAthleteByID(ctx context.Context, id int64) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, getAthleteByID, id)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
	)
	return i, err
}

const getMeetByID = `-- name: GetMeetByID :one
SELECT id, name, date, location FROM meets WHERE id = ? LIMIT 1
`

func (q *Queries) GetMeetByID(ctx context.Context, id int64) (Meet, error) {
	row := q.db.QueryRowContext(ctx, getMeetByID, id)
	var i Meet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Location,
	)
	return i, err
}

const getResultByID = `-- name: GetResultByID :one
SELECT id, athlete_id, meet_id, time, place FROM results WHERE id = ? LIMIT 1
`

func (q *Queries) GetResultByID(ctx context.Context, id int64) (Result, error) {
	row := q.db.QueryRowContext(ctx, getResultByID, id)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.MeetID,
		&i.Time,
		&i.Place,
	)
	return i, err
}

const getResultsByAthlete = `-- name: GetResultsByAthlete :many
SELECT r.id, r.athlete_id, r.meet_id, r.time, r.place, m.name as meet_name, m.date as meet_date
FROM results r
JOIN meets m ON r.meet_id = m.id
WHERE r.athlete_id = ?
ORDER BY m.date
`

type GetResultsByAthleteRow struct {
	ID        int64
	AthleteID sql.NullInt64
	MeetID    sql.NullInt64
	Time      sql.NullString
	Place     sql.NullInt64
	MeetName  string
	MeetDate  sql.NullString
}

func (q *Queries) GetResultsByAthlete(ctx context.Context, athleteID sql.NullInt64) ([]GetResultsByAthleteRow, error) {
	rows, err := q.db.QueryContext(ctx, getResultsByAthlete, athleteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultsByAthleteRow
	for rows.Next() {
		var i GetResultsByAthleteRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Time,
			&i.Place,
			&i.MeetName,
			&i.MeetDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResultsByMeet = `-- name: GetResultsByMeet :many
SELECT r.id, r.athlete_id, r.meet_id, r.time, r.place, a.name as athlete_name
FROM results r
JOIN athletes a ON r.athlete_id = a.id
WHERE r.meet_id = ?
ORDER BY r.place
`

type GetResultsByMeetRow struct {
	ID          int64
	AthleteID   sql.NullInt64
	MeetID      sql.NullInt64
	Time        sql.NullString
	Place       sql.NullInt64
	AthleteName string
}

func (q *Queries) GetResultsByMeet(ctx context.Context, meetID sql.NullInt64) ([]GetResultsByMeetRow, error) {
	rows, err := q.db.QueryContext(ctx, getResultsByMeet, meetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResultsByMeetRow
	for rows.Next() {
		var i GetResultsByMeetRow
		if err := rows.Scan(
			&i.ID,
			&i.AthleteID,
			&i.MeetID,
			&i.Time,
			&i.Place,
			&i.AthleteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAthlete = `-- name: UpdateAthlete :one
UPDATE athletes
SET name = ?, grade = ?, personal_record = ?, events = ?
WHERE id = ?
RETURNING id, name, grade, personal_record, events
`

type UpdateAthleteParams struct {
	Name           string
	Grade          sql.NullInt64
	PersonalRecord sql.NullString
	Events         sql.NullString
	ID             int64
}

func (q *Queries) UpdateAthlete(ctx context.Context, arg UpdateAthleteParams) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, updateAthlete,
		arg.Name,
		arg.Grade,
		arg.PersonalRecord,
		arg.Events,
		arg.ID,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Grade,
		&i.PersonalRecord,
		&i.Events,
	)
	return i, err
}

const updateMeet = `-- name: UpdateMeet :one
UPDATE meets
SET name = ?, date = ?, location = ?
WHERE id = ?
RETURNING id, name, date, location
`

type UpdateMeetParams struct {
	Name     string
	Date     sql.NullString
	Location sql.NullString
	ID       int64
}

func (q *Queries) UpdateMeet(ctx context.Context, arg UpdateMeetParams) (Meet, error) {
	row := q.db.QueryRowContext(ctx, updateMeet,
		arg.Name,
		arg.Date,
		arg.Location,
		arg.ID,
	)
	var i Meet
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Date,
		&i.Location,
	)
	return i, err
}

const updateResult = `-- name: UpdateResult :one
UPDATE results
SET athlete_id = ?, meet_id = ?, time = ?, place = ?
WHERE id = ?
RETURNING id, athlete_id, meet_id, time, place
`

type UpdateResultParams struct {
	AthleteID sql.NullInt64
	MeetID    sql.NullInt64
	Time      sql.NullString
	Place     sql.NullInt64
	ID        int64
}

func (q *Queries) UpdateResult(ctx context.Context, arg UpdateResultParams) (Result, error) {
	row := q.db.QueryRowContext(ctx, updateResult,
		arg.AthleteID,
		arg.MeetID,
		arg.Time,
		arg.Place,
		arg.ID,
	)
	var i Result
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.MeetID,
		&i.Time,
		&i.Place,
	)
	return i, err
}
